package com.x.processplatform.core.entity.content;

import com.x.base.core.entity.SliceJpaObjectStatic;
import com.x.processplatform.core.entity.element.ActivityType;
import java.util.Date;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(TaskCompleted.class)
public class TaskCompletedStatic extends SliceJpaObjectStatic {
    public static volatile SingularAttribute<TaskCompleted, String> activity;
    public static volatile SingularAttribute<TaskCompleted, String> activityAlias;
    public static volatile SingularAttribute<TaskCompleted, String> activityDescription;
    public static volatile SingularAttribute<TaskCompleted, String> activityName;
    public static volatile SingularAttribute<TaskCompleted, String> activityToken;
    public static volatile SingularAttribute<TaskCompleted, ActivityType> activityType;
    public static volatile SingularAttribute<TaskCompleted, String> application;
    public static volatile SingularAttribute<TaskCompleted, String> applicationAlias;
    public static volatile SingularAttribute<TaskCompleted, String> applicationName;
    public static volatile SingularAttribute<TaskCompleted, Boolean> booleanValue01;
    public static volatile SingularAttribute<TaskCompleted, Boolean> booleanValue02;
    public static volatile SingularAttribute<TaskCompleted, Boolean> completed;
    public static volatile SingularAttribute<TaskCompleted, Date> completedTime;
    public static volatile SingularAttribute<TaskCompleted, String> completedTimeMonth;
    public static volatile SingularAttribute<TaskCompleted, String> creatorIdentity;
    public static volatile SingularAttribute<TaskCompleted, String> creatorPerson;
    public static volatile SingularAttribute<TaskCompleted, String> creatorUnit;
    public static volatile SingularAttribute<TaskCompleted, String> currentActivityName;
    public static volatile SingularAttribute<TaskCompleted, Date> dateTimeValue01;
    public static volatile SingularAttribute<TaskCompleted, Date> dateTimeValue02;
    public static volatile SingularAttribute<TaskCompleted, Date> dateTimeValue03;
    public static volatile SingularAttribute<TaskCompleted, Date> dateTimeValue04;
    public static volatile SingularAttribute<TaskCompleted, Date> dateTimeValue05;
    public static volatile SingularAttribute<TaskCompleted, Date> dateValue01;
    public static volatile SingularAttribute<TaskCompleted, Date> dateValue02;
    public static volatile SingularAttribute<TaskCompleted, String> distinguishedName;
    public static volatile SingularAttribute<TaskCompleted, Double> doubleValue01;
    public static volatile SingularAttribute<TaskCompleted, Double> doubleValue02;
    public static volatile SingularAttribute<TaskCompleted, Double> doubleValue03;
    public static volatile SingularAttribute<TaskCompleted, Double> doubleValue04;
    public static volatile SingularAttribute<TaskCompleted, Double> doubleValue05;
    public static volatile SingularAttribute<TaskCompleted, Long> duration;
    public static volatile SingularAttribute<TaskCompleted, String> empowerFromIdentity;
    public static volatile SingularAttribute<TaskCompleted, String> empowerToIdentity;
    public static volatile SingularAttribute<TaskCompleted, Date> expireTime;
    public static volatile SingularAttribute<TaskCompleted, Boolean> expired;
    public static volatile SingularAttribute<TaskCompleted, String> id;
    public static volatile SingularAttribute<TaskCompleted, String> identity;
    public static volatile SingularAttribute<TaskCompleted, String> job;
    public static volatile SingularAttribute<TaskCompleted, Boolean> joinInquire;
    public static volatile SingularAttribute<TaskCompleted, String> label;
    public static volatile SingularAttribute<TaskCompleted, Boolean> latest;
    public static volatile SingularAttribute<TaskCompleted, Long> longValue01;
    public static volatile SingularAttribute<TaskCompleted, Long> longValue02;
    public static volatile SingularAttribute<TaskCompleted, Long> longValue03;
    public static volatile SingularAttribute<TaskCompleted, Long> longValue04;
    public static volatile SingularAttribute<TaskCompleted, Long> longValue05;
    public static volatile SingularAttribute<TaskCompleted, String> mediaOpinion;
    public static volatile SingularAttribute<TaskCompleted, String> opinion;
    public static volatile SingularAttribute<TaskCompleted, String> opinionLob;
    public static volatile SingularAttribute<TaskCompleted, String> person;
    public static volatile SingularAttribute<TaskCompleted, String> pressActivityToken;
    public static volatile SingularAttribute<TaskCompleted, Integer> pressCount;
    public static volatile SingularAttribute<TaskCompleted, Date> pressTime;
    public static volatile SingularAttribute<TaskCompleted, String> process;
    public static volatile SingularAttribute<TaskCompleted, String> processAlias;
    public static volatile SingularAttribute<TaskCompleted, String> processName;
    public static volatile SingularAttribute<TaskCompleted, String> processingType;
    public static volatile SingularAttribute<TaskCompleted, TaskCompletedProperties> properties;
    public static volatile SingularAttribute<TaskCompleted, Date> retractTime;
    public static volatile SingularAttribute<TaskCompleted, String> routeAlias;
    public static volatile SingularAttribute<TaskCompleted, String> routeName;
    public static volatile SingularAttribute<TaskCompleted, String> serial;
    public static volatile SingularAttribute<TaskCompleted, Date> startTime;
    public static volatile SingularAttribute<TaskCompleted, String> startTimeMonth;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue01;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue02;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue03;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue04;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue05;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue06;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue07;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue08;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue09;
    public static volatile SingularAttribute<TaskCompleted, String> stringValue10;
    public static volatile SingularAttribute<TaskCompleted, String> task;
    public static volatile SingularAttribute<TaskCompleted, Date> timeValue01;
    public static volatile SingularAttribute<TaskCompleted, Date> timeValue02;
    public static volatile SingularAttribute<TaskCompleted, String> title;
    public static volatile SingularAttribute<TaskCompleted, String> unit;
    public static volatile SingularAttribute<TaskCompleted, Date> viewTime;
    public static volatile SingularAttribute<TaskCompleted, String> work;
    public static volatile SingularAttribute<TaskCompleted, String> workCompleted;

    public TaskCompletedStatic() {
    }
}
